### ISSUE TITLE
Could not find or load main class SeqFormatConvert.seqFactory.SeqConverter?

### ISSUE THREAD

**Issue by xiekunwhy** [BioEasy/EasyCodeML#1]
Hi,
When I run this java -cp /Bio/User/kxie/software/EasyCodeML_v1.0/EasyCodeML.jar SeqFormatConvert.seqFactory.SeqConverter, EasyCodeML told me Could not find or load main class SeqFormatConvert.seqFactory.SeqConverter.
Was I miss something?

**Comment by CJ-Chen** [comment]
please update the EasyCodeML.jar file and try "java -cp C:\Users\CJ\Desktop\EasyCodeML.jar SeqFormatConvert.seqFactory.SeqConverter -inFile"
