### ISSUE TITLE
Amino acid-codon correlation for branch-site model

### ISSUE THREAD

**Issue by hventhur** [BioEasy/EasyCodeML#10]
Dear developers,

First of all thank you very much for EasyCODEML.
I've been facing ab issue while running branch-site model for a set of 9 sequences that I've been working with, which is that PSSs do not correlate with the actual amino acid sequence of my proteins. Instead, I found that they are misplaced. I read in a previous issue that EasyCODEML recognizes the first sequence for PSSs. However, I still have the same problem. Thus, my questions are, how I can manage the files to ensure correlation between PSSs and the actual amino acid sequence? Should the first sequence be in the amino acid alignment or codon alignment? The newick tree, should be made from codon alignment using codon models? I've tried many combinations haha.

Many thanks in advance
Cheers
Herbert

**Comment by BioEasy** [comment]
Hi Herbert, 
Thanks for your interest in our EasyCodeML. To correlate with the actual amino acid sequence of your proteins , please uncheck the option "Clean data" prior to analysis. Note that if the “Clean data”option is enabled, all sites with ambiguity characters and alignment gaps will be removed from the sequence alignment. 

All the best,
Fangluan
