### ISSUE TITLE
Do not have any resolved nucleotides

### ISSUE THREAD

**Issue by Citugulia40** [BioEasy/EasyCodeML#11]
Dear Developer,
I am having a codon alignment file of my sequences that I have converted by PAL2NAL from amino acid alignment and a tree file in newick format.
I am running the site Model and checked the sequence and tree file, which is showing ok status to both the files but when I am running CodeML, I am getting an error 

"227 out of 227 do not have any resolved nucleotides. Givingup"

Please help

Thanks and regards

**Comment by BioEasy** [comment]
Hi, thanks for your questions. From the error message, it seems that the nucleotide sequences does not share any identity among the taxa in the alignment. In this case, amino sequence should be used instead the nucleotide sequences. Please run the analysis using the software codeML in the package PAML (Unfortunately, the current version of EasyCodeML does not  perform the analysis  in the GUI). 

All the best,
Fangluan
