### ISSUE TITLE
Error opening EasyCodeml in mac

### ISSUE THREAD

**Issue by GarlicPaasta** [BioEasy/EasyCodeML#12]
Hi, I was able to find and download the EasyCodeml .jar file, but when I try to launch it from Finder, it gives two errors. The first one says 'Can't found 'codeml.exe' or 'chi2.exe', and the second one says 'Could NOT found the Custom Files in the same directory of EasyCodeML.jar.'

I also tried opening the jar file from my mac terminal. However the same errors appeared. 

(base) leontang@Leons-MacBook-Pro ~ % java -jar EasyCodeML.jar
chmod: /Users/leontang/Preset/codeml.exe: No such file or directory
chmod: /Users/leontang/Preset/chi2.exe: No such file or directory

There are a set of chi2.exe and codeml.exe files in my main folder, I assume I need to do something to with these two exe files, but I''m confused as to what that is. Any help would be appreciated.

**Comment by ergarzaz** [comment]
I had the same issue until I realized it was a problem with how I was downloading the files. 

My solution:
Go to the DownGit site and create a directory download link. Afterwards, you can just click the download button and you will see a copy of the entire EasyCodeML directory in your Downloads.

DownGit:       https://downgit.github.io/
Directory link to copy:         https://github.com/BioEasy/EasyCodeML

For more info on downloading a single folder or directory from a GitHub repo, visit this link:
https://stackoverflow.com/questions/7106012/download-a-single-folder-or-directory-from-a-github-repo
