### ISSUE TITLE
No output - Reg.

### ISSUE THREAD

**Issue by bioramg** [BioEasy/EasyCodeML#13]
Hells sir,
I am trying to find out the positive selection value for the chloroplast protein-coding gene.  I checked files and its ready. When I execute site model, the program is running in a few minutes and status is complete. But there is no output at Likelihood Ration Test column. What could be the problem.
Aligned file:
>amarae
ATGAGAATAAATTTTACTACTTCGGATCCAGAGGTTTCGATACGTGAAAAAAAAAATCTGGGACGTATCGCCCAAATAATTGGTCCGGTACTGGATGTAGCCTTTCCCCCGGGTAAGATGCCTAATATTTACAATGCTCTGGTGGTTAAGGGTCGAGATACTCTTGGTCAAGAAATTAATGTGACTTGTGAAGTACAGCAATTATTAGGAAATAATCGAGTTAGAGCTGTAGCTATGAGTGCGACAGAGGGTTTAAAGAGAGGAATGGACGTGGTTGATATGGGAAATCCTCTAAGTGTTCCAGTCGGCGGAGCGACTCTAGGACGAATTTTCAACGTGCTTGGGGAACCTGTTGATAATTTAGGTCCTGTCGATACTCGCACAACATCTCCTATCCATAAATCCGCGCCTGCTTTTATACAATTAGATACAAAATTATCTATTTTTGAAACAGGAATTAAAGTAGTAGATCTTTTGGCCCCTTATCGTCGTGGGGGAAAAATCGGACTATTCGGTGGGGCTGGCGTGGGTAAAACAGTACTAATTATGGAATTGATCAACAACATTGCCAAAGCTCATGGTGGTGTATCCGTATTTGGTGGAGTAGGCGAACGGACTCGTGAAGGAAATGATCTTTACATGGAAATGAAAGAATCTGGAGTCATTAATGAACAAAATCTTGCGGAATCAAAAGTGGCCCTAGTCTACGGTCAGATGAATGAACCGCCGGGAGCTCGTATGAGAGTTGGTCTGACTGCCTTAACTATGGCCGAATATTTCCGAGATGTTAATGAGCAAGACGTACTTCTATTTATCGACAATATCTTCCGTTTCGTACAAGCAGGATCCGAGGTATCTGCTTTATTGGGTAGAATGCCTTCTGCTGTGGGTTATCAACCCACCCTTAGTACCGAAATGGGTACTTTACAAGAAAGAATTACTTCTACGAAAAAAGGGTCCATAACCTCTATTCAAGCAGTTTATGTACCTGCCGACGATTTGACTGACCCCGCTCCTGCCACCACATTTGCACATTTAGATGCGACTACCGTACTATCAAGAGGATTATCTGCCAAAGGTATATCTATCCAGCGGTAG-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
>NC_049603
ATGAGAATAAATCTTACTACTCCGGATCCAGACGTTTCGATACGTGAAAAAAAAAATCTGGGACGTATCGCCCAAATCATTGGTCCGGTACTGGATGTAGCCTTTCCCCCGGGTAAGATGCCTAATATTTACAATGCTCTGGTGGTTAAGGGTCGAGATACTCTTGGTCAAGAAATTAATGTGACTTGTGAAGTACAGCAATTATTAGGAAATAATCGAGTTAGAGCTGTAGCTATGAGTGCGACAGAGGGTTTAAAGAGAGGAATGGACGTGGTTGATATGGGAAATCCTCTAAGTGTTCCAGTCGGCGGAGCGACTCTAGGACGAATTTTCAACGTGCTTGGGGAACCTGTTGATAATTTAGGTCCTGTCGATACTCGCACAACATCTCCTATCCATAAATCCGCGCCTGCTTTTATACAATTAGATACAAAATTATCCATTTTTGAAACAGGAATTAAAGTAGTAGATCTTTTGGCCCCTTATCGTCGTGGGGGAAAAATCGGACTATTCGGTGGGGCTGGCGTGGGTAAAACAGTACTAATTATGGAATTGATCAACAACATTGCCAAAGCTCATGGTGGTGTATCCGTATTTGGTGGAGTAGGCGAACGGACTCGTGAAGGAAATGATCTTTACATGGAAATGAAAGAATCTGGAGTCATTAATGAACAAAATCTTGCGGAATCAAAAGTGGCCCTAGTCTACGGTCAGATGAATGAACCGCCGGGAGCTCGTATGAGAGTTGGTCTGACTGCCTTAACTATGGCAGAATATTTCCGAGATGTTAATGAGCAAGACGTACTTCTATTTATCGACAATATCTTCCGTTTCGTACAAGCAGGATCCGAGGTATCCGCTTTATTGGGTAGAATGCCTTCTGCTGTGGGTTATCAACCCACCCTTAGTACCGAAATGGGTACTTTACAAGAAAGAATTACTTCTACGAAAAAAGGGTCCATAACCTCTATTCAAGCAGTTTATGTACCTGCAGACGATTTGACTGACCCCGCTCCTGCCACCACATTTGCACATTTAGATGCGACTACCGTACTATCAAGAGGATTAGCTGCCAAAGG--TATTTATCCAGCGGTAGATCCTTTAGATTCAACGTCAACTATGCTACAACCTCGAATCGTTGGCGAAGAACATTATGAAACTGCGCAACAAGTCAAGCAAACTTTACAACGTTACAAGGAGCTTCAGGACATTATAGCTATCCTGGGGTTGGACGAATTATCCGAAGAGGATCGTTTAACCGTAGCAAGAGCACGAAAAATTGAGCGTTTCTTATCACAACCCTTTTTCGTAGCCGAAGTATTTACAGGTTCTCCGGGAAAATATGTTGGTCTAGCGGAAACAATTAGAGGGTTTAAATTGATCCTTTCCGGAGAATTTGATTCTCTTCCTGAACAGGCCTTTTACTTAGTGGGTAACATCGATGAAGCTACTGCGAAGGCTACAAACTTAGAAATGGAGAGTAAATTGAAGAAATGA

Netwick format:
((NC_026446:0.002006986557366933,(((MF405340:0.0020068659141614744,NC_049606:1.00000050002909E-6):1.00000050002909E-6,(NC_049620:6.677875390108166E-4,(NC_026445:0.0013361341434836099,NC_049603:6.680267411560315E-4):1.00000050002909E-6):0.002676480845530165):6.682470251260322E-4,((NC_036963:1.00000050002909E-6,NC_049607:1.00000050002909E-6):0.0067402793090829425,(NC_049617:1.00000050002909E-6,NC_049610:1.00000050002909E-6):0.0033457175998536093):1.00000050002909E-6):1.00000050002909E-6):0.002007108295378454,((fallax:1.00000050002909E-6,occulta:1.00000050002909E-6):0.00403256046267553,(amarae:9.140016459276029E-4,NC_036964:1.00000050002909E-6):6.67693480686542E-4):0.0013409821322993183,NC_049605:1.00000050002909E-6);

However, I have used the same program previously and obtained results. But, I could not troubleshoot and what could be the problem?
I am looking forward to hearing from you.
Thank you.

**Comment by BioEasy** [comment]
HI, thanks for your questions. To run a CodeML analysis, a multiple sequence alignment and a phylogenetic tree are required, but for the the phylogenetic tree, only the topology was included the analysis (the branch lengths were not to be used). Therefore, it is strongly recommended to keep only the taxa name (remove the  branch lengths or bootstrap values on each node). To do this, please clean the tree using the TreeCleaner implemented in the menu 'Tools'.

All the best,
Fangluan
