### ISSUE TITLE
This binary is not suitable for the Linux environment

### ISSUE THREAD

**Issue by starsareintherose** [BioEasy/EasyCodeML#16]
This binary is not suitable for the Linux environment
exe file is not for Linux. please give a specific option to determine the binary path
![2022-03-20 19-43-01屏幕截图](https://user-images.githubusercontent.com/37733075/159179937-db8c961c-4071-4c52-be62-e8059d482d9a.png)

**Comment by BioEasy** [comment]
The package you downloaded seems to be not complete. Please 'code' to download the Zip file (EasyCodeML-master.zip) and unpacked it to the local directory. Just click the EasyCodeML.jar to run a codeml analysis (Java library should be install prior the click).

**Comment by starsareintherose** [comment]
If I package the essential files into `/usr/share/EasyCodeML`, it will also report same error
```
ls -al /usr/share/EasyCodeML/Preset
lrwxrwxrwx 1 root root   13 Aug 17 11:14 chi2.exe -> /usr/bin/chi2
lrwxrwxrwx 1 root root   15 Aug 17 11:14 codeml.exe -> /usr/bin/codeml
```
