### ISSUE TITLE
 easy codeml for aminoacid sequences 

### ISSUE THREAD

**Issue by PPrabhu1997** [BioEasy/EasyCodeML#18]
Can we use EasyCodeML to detect selection in aminoacid sequeces? I made a phylogentic tree of 72 OTUs for specific enzyme and the tree was cleaned using the tree cleaner implemented in Easycodeml and I implemented a branch site model for detecting the selection. I was unable to lable the tree and the unable to proceed. Could you please help me with this ?

**Comment by BioEasy** [comment]
EasyCodeML can be run in the Custom Mode using amino acid sequences, but not the Preset Mode.
