### ISSUE TITLE
Name check error message in EasyCodeML

### ISSUE THREAD

**Issue by schultzt23** [BioEasy/EasyCodeML#19]
I am trying to use EasyCodeML for the first time.  Are dashes "-" allowed in taxon names in EasyCodeML? They are allowed in PAML, so I assume they are allowed in ECML. I am submitting a tree and an alignment matrix to EasyCodeML. I am pretty sure they are both PAML-acceptable in terms of taxon names. But I when I hit "Check" I keep getting an error message that the names in the matrix and in the tree don't match. I really can't figure out why I'm getting this message, unless dashes are not allowed in names.

**Comment by schultzt23** [comment]
Just as a test, I eliminated all the dashes from the taxon names and I am STILL getting the error message that the taxon names don't match . . . but they do.  The error message lists what appears to be every taxon in the data set.

**Comment by BioEasy** [comment]
To solve your question, could you please send me the data files and attach here? 

All the best
Fangluan
