### ISSUE TITLE
Error: Cannot load from object array because "bmresult" is null

### ISSUE THREAD

**Issue by coliverbrown** [BioEasy/EasyCodeML#21]
I am currently trying to run a branch model test using the preset option but the LRT window is not being auto populated with values after running the model. The error "Cannot load from object array because "bmresult" is null" is displayed in Terminal but I do not know how to fix this. I can see output files being placed in my working directory and none of them are empty. Is there a way to fix this error code? Thanks

**Comment by lil-qorgi** [comment]
I encountered the same issue. I noted that I had existing files in the folder that might have collided with the files that were going to be generated. The solution was to remove every file from the directory to be used as the "Working Directory." Maybe this will help.

**Comment by lil-qorgi** [comment]
I encountered the same issue. The issue is that the branch model requires that you label the tree first with at least one foreground branch. I used the 'Label' button to label the tree before running. This resolved the issue for me.
