### ISSUE TITLE
Error #

### ISSUE THREAD

**Issue by maed-sudo** [BioEasy/EasyCodeML#23]
I 'm trie used the program, but it finalize with an error that i don't understand. It's (Seq #38 occurs more than once in the tree) but this sequence aren't a repetition. 
Some one know how to solve this?

**Comment by CJ-Chen** [comment]
意思就是你有两个序列的 ID 是一样的。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月3日(星期五) 上午7:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [BioEasy/EasyCodeML] Error # (Issue #23)





 
I 'm trie used the program, but it finalize with an error that i don't understand. It's (Seq #38 occurs more than once in the tree) but this sequence aren't a repetition.

**Comment by maed-sudo** [comment]
> 意思就是你有两个序列的 ID 是一样的。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年3月3日(星期五) 上午7:18 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [BioEasy/EasyCodeML] Error # (Issue #23) I 'm trie used the program, but it finalize with an error that i don't understand. It's (Seq #38 occurs more than once in the tree) but this sequence aren't a repetition. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

But I don't have same id. You know how many caracters the program considering with with ID?

**Comment by maed-sudo** [comment]
Hello CJ-Chen, 

My name is Maria and I'm mastering student of UFRGS in Brazil. I tried use de EasyCodeML but in differents seqs file appers the same error. It tells me that have a repetition same sequence. My doubt: if the error can be occours when sequences may be very closelly and have just few sites diferents? 

Because the program give the error with sequences that related. And I don't know how to solve this.

Thank you for taking the time to answer me, if you can help I appreciate it.
