### ISSUE TITLE
作者您好，下载完并启动EasyCodeM.jar时，为什么会出现以下俩个话框？如何解决？

### ISSUE THREAD

**Issue by nmsl0522** [BioEasy/EasyCodeML#24]
①Can't found 'codeml.exe' or 'chi2.exe'
Please make sure the program packages is complete.Or Most Fucntions of EasyCodeML will Fail.

②Could NOT found the Custom Files in the same directory of EasyCodeML.jar.Please make sure the program packages is complete.
Or Most Fucntions of EasyCodeML will Fail.

**Comment by mosy550** [comment]
直接在code下载zip解压就没有这个问题

**Comment by MYP0130** [comment]
请问您解决这个问题了吗，我直接下载zip到ubuntu里可以运行，但是在服务器上就不行

**Comment by nmsl0522** [comment]
并没有，我放弃了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月30日(星期二) 晚上10:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [BioEasy/EasyCodeML] 作者您好，下载完并启动EasyCodeM.jar时，为什么会出现以下俩个话框？如何解决？ (Issue #24)





 
请问您解决这个问题了吗，我直接下载zip到ubuntu里可以运行，但是在服务器上就不行

**Comment by CJ-Chen** [comment]
> 并没有，我放弃了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年5月30日(星期二) 晚上10:19 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [BioEasy/EasyCodeML] 作者您好，下载完并启动EasyCodeM.jar时，为什么会出现以下俩个话框？如何解决？ (Issue #24) 请问您解决这个问题了吗，我直接下载zip到ubuntu里可以运行，但是在服务器上就不行 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Emmm，这个应该是电脑安全设置的问题，直接用 .bat 脚本启动试试。最好还是到社群交流。
