### ISSUE TITLE
Seqformat Converter Error

### ISSUE THREAD

**Issue by lbillington** [BioEasy/EasyCodeML#3]
Hi

I have been converting fasta files in paml format using the Seqformat Converter that downloaded with EasyCode. However, when I try to run the programme, I get the following error 

'Reading sequences, sequential format..
Reading seq # 1: H5N1_Avian_AF046085_A/Chicken/Hong_Kong/220/97__Ho     

Error in sequence data file: O at 4 seq 1.
Make sure to separate the sequence from its name by 2 or more spaces.'

I've also tried another online fasta to paml converter, which shows 2 spaces between the name and sequence in its output file, but still get the error. Can someone explain where I'm going wrong?

Thanks
LB

**Comment by BioEasy** [comment]
Hi LB,
Thanks for your interests in our EasyCodeML. Is your data amino acids sequence? Currently, the preset mode for EasyCodeML only supports a codeml analysis using the coding nucleotide sequence, but the custom mode can run a codeml analysis using the amino acids sequence. I hope this is helpful!

All the best,
Fangluan

**Comment by lbillington** [comment]
Hi Fangluan, 

I am using coding nucleotide sequences for EasyCodeML. I read somewhere that paml accepts 30 characters only for a sequence name - is EasyCodeML the same?

Thanks

LB

**Comment by BioEasy** [comment]
Hi LB,
Thanks for your response. Could you please send me the files? I will check them.

All the best,
Fangluan

**Comment by lbillington** [comment]
Hi Fangluan,

This is the fasta file, the paml file produced by the format converter and the newick tree.

Thanks,

LB

**Comment by lbillington** [comment]
Not sure if the files attached properly, as my email threw an error

[GitHub.zip](https://github.com/BioEasy/EasyCodeML/files/3697615/GitHub.zip)

**Comment by BioEasy** [comment]
Hi LB,
Sorry for the delayed responses. I have go through your attached files and the reason for the error is sequence name and tree taxon name.  In particularly,  the tree seem to be in figtree format but  not standard Newick format. In addition,  there are many illegal characters in the taxon names (such as |,  / ).  To solve it, my suggestion is to rename the sequence name and tree taxon name to a more simplified one during performing phylogenetic analysis and CodeML analysis. Note that the tree in newick used in CodeML analysis does not contain bootstrap values and branch lengths -- you can export into newick format in Figtree and save the name as xxxx.nwk, then open with MEGA and uncheck the option of  'bootstrap values' and 'branch lengths'. 

PS. Not worry the short name in the tree, since we are easy to restore the long name in Figtree using 'Import Annotations from the File menu'). 

All the best,
Fangluan

**Comment by Corner1220** [comment]
Hi LB,
I have been converting clustal files into paml format using the Seqformat Converter that downloaded with EasyCode. However, when I press the Start Button, no output file appeared.
I don't quite know what's the matter.

**Comment by kshLab** [comment]
Same problem here with fasta input file!

**Comment by BioEasy** [comment]
> Same problem here with fasta input file!
It's strongly recommended to rename sequence name to simplified one (i.e. using Accession), which will helpful for the subsequent CodeML analysis.

**Comment by BioEasy** [comment]
> Hi LB,
> I have been converting clustal files into paml format using the Seqformat Converter that downloaded with EasyCode. However, when I press the Start Button, no output file appeared.
> I don't quite know what's the matter.
Cloud you sent me this alignment in CLUSTAL? Let me check it.
Raindyok(at)qq.com

**Comment by lbillington** [comment]
Hi BioEasy, 

I'm working from home due to the pandemic and all my bioinformatics files are on my office computer because my laptop doesn't have the processing power. I can't send you my alignment, sorry.

**Comment by kshLab** [comment]
This is not the problem.

Kathrin Stanger-Hall, PhD
Department of Plant Biology
4510 Miller Plant Sciences Building
University of Georgia, Athens 30602
ksh@uga.edu
Stanger-Hall Lab <http://research.franklin.uga.edu/stanger-hall/>

**Comment by schultzt23** [comment]
I am not sure this string is still active, but I have a question.  Are dashes "-" allowed in taxon names in EasyCodeML?  They are allowed in PAML.  I am submitting a tree and an alignment matrix to EasyCodeML.  I am pretty sure they are both PAML-acceptable in terms of taxon names.  But I when I hit "Check" I keep getting an error message that the names in the matrix and in the tree don't match.  I really can't figure out why I'm getting this message, unless dashes are not allowed in names.

**Comment by NathanPaiva** [comment]
olá pessoal ,
