### ISSUE TITLE
Positive sites labelled as "Not Allowed"

### ISSUE THREAD

**Issue by Steven-Kemp** [BioEasy/EasyCodeML#5]
Hi,

After running EasyCodeML with the default settings (having provide a ML tree and codon-aligned nucleotide fasta) then program happily ran and spat out the attached output. I wonder why it has only given me positive sites according to the M8 model and has reported "Not Allowed" for models M0, M1a and M7?

Perhaps you might be able to help me?

Best wishes,
Steve

[22763_pol.xls.zip](https://github.com/BioEasy/EasyCodeML/files/5023991/22763_pol.xls.zip)

**Comment by BioEasy** [comment]
Hi Steve,
The models of M1a and M7 are under the assumption of (nearly) neutral evolution, so they are not allowed for detection of positive selection. In addition, the M0–M3 comparison does also not allow detection of positive selection, as mentioned in the  footnote in Table 2 in our EasyCodeML paper (https://onlinelibrary.wiley.com/doi/abs/10.1002/ece3.5015).

All the best,
Fangluan
