### ISSUE TITLE
EasyCodeML in command line ? 

### ISSUE THREAD

**Issue by StromTroopers** [BioEasy/EasyCodeML#6]
Hello everyone, first of all I would like to thank you for developing a tool like EasyCodeML, really efficient and very easy to use. 

But I now need to use codeml in a large dataset (large phylogeny of 100 species with long alignments), and it's true that the parallelization implemented in EasyCodeML is very interesting but the user friendly aspect becomes limiting when you want to process a large dataset (several hundreds of codeml runs to do).
So I was wondering if you plan to make EasyCodeML available on the command line as well? 

Thank you and have a nice day

**Comment by VinayTeja-P** [comment]
Is it possible to run command line on HPC cluster with red hat ?

**Comment by BioEasy** [comment]
> Is it possible to run command line on HPC cluster with red hat ?
It is not supported to run command line when using EasyCodeML.
