### ISSUE TITLE
Labelling Tree

### ISSUE THREAD

**Issue by thulasis** [BioEasy/EasyCodeML#7]
Hi

Thank you for developing easycodeml.
I was trying to use clademodel analysis and unable to label clades. When I click label, it was not directing me to UI to see the tree and label it as shown in publication. When I proceed to run codeml, saying labelled.txt was not found. I am using the latest version. 
Even sequence converter is also not giving the output. I couldn't able to see UI for conversion and when I did on command line, no output is generated.

what might be the issue?
Please solve ASAP.

Thank you

Sincerel

**Comment by BioEasy** [comment]
Hi, 
In EasyCodeML, the tree in Newick does not contain any value (i.e. branch lengths or bootstrap values) ,please check it carefully. BTW, a tree cleaner implemented in Tools menu can be used to to remove the values in the tree. Two example tree s could be tested for clade model. For the sequence converter, a standard fasta format sequence was strongly recommended to be original file to be converted. 

All the best,
Fangluan

**Comment by thulasis** [comment]
Hi

Thank you for your jiffy reply.
I didn't expect this fast. 
I rectified the issues on my side. I am sorry..the problem with input tree file. I cleaned the tree and then modified the IDs. Then it started working. 

Thank you so much.

Sincerely
