### ISSUE TITLE
Where is de Lnl for each model in Sites Models?

### ISSUE THREAD

**Issue by MauriAndresMU1313** [BioEasy/EasyCodeML#8]
When I run the sites-models I expect the Lnl for each model in the output file, however, this important information never prints in any output file. This is important for the LRT test, I need this to continue with my project. 
Any idea or comment on this issue? 
I´m looking for something like this:

````
Model` 0: one-ratio ...
**lnL(ntime: 23 np: 25): -1133.892429** +0.000000 ...
kappa (ts/tv) = 2.27532 omega (dN/dS) = 0.91089
branch = 14..1
t = 0.024
N = 234.4
S = 38.6
dN/dS = 0.9109
dN = 0.0078
dS = 0.0086
N*dN =  1.8 0.3
S*dS = 0.3

> Model 1: NearlyNeutral (2 categories)
**lnL(ntime: 23 np: 26): -1110.361397** +0.000000 ...
kappa (ts/tv) = 2.28035 dN/dS (w) for site classes (K=2) p: 0.49440 0.50560 w: 0.08871 1.00000 ...
branch = 14..1
t = 0.025
N = 234.4
S = 38.6
dN/dS = 0.9109
dN = 0.0078
dS = 0.0086
N*dN = 1.8
S*dS = 0.3
```

Model 2....
Model 7 ...
Model 8...

Thank!

**Comment by BioEasy** [comment]
Hi, this information was presented in the file named 'xxx.mlc', which is located in each model directory (i.e. M8_mlc in the M8 folder).
All the best

**Comment by MauriAndresMU1313** [comment]
My outputs are incomplete in this case, because I ran Sites-models a lot of times, however never print the Lnl values for each model. 
Could you help me whit that? 
Maybe with any indication with de control file for Sites-models?
I have 727 sequences in this case, in case you want more details I could share the files of my data. 
Or any comment is welcome. I really need these values to finish a part of my project.

**Comment by MauriAndresMU1313** [comment]
Please, any advice for this? 
I need the Lnl values to finish my project.
How can I say to the program will print the Lnl values in the output?

**Comment by BioEasy** [comment]
Hi, the LnL values can be obtained only when the task for CodeML is complete. From the description (the outputs are incomplete), I think the CodeML analysis for your data set is still running and not finished . Note that CodeML analyses are very computationally intensive, especially for the large data set (i.e. 727). For example, I have run a CodeML analysis for 1 months and it is still running (137 sequences, with the length of 816 bp).
