### ISSUE TITLE
Present mode site model result interpretation 

### ISSUE THREAD

**Issue by huiyus16** [BioEasy/EasyCodeML#9]
Hi,
Thank you so much for inventing this interface! 
I used present mode with site model to run a file which contains eight sequences. For each sequence, the length is 3676504. I wanted to detect the positive selected genes, and here is what was shown in the excel file: 
1 P 0.656,
2 L 0.970*,
3 G 0.798,
4 I 0.937,
...,
879 K 0.998**,
880 E 0.986*,
881 A 1.000
I have trouble interpreting this result from the excel file after running the LRT analysis.
Does the number in the front means the nucleotide position in the sequence?

Thank you so much for your help!

**Comment by BioEasy** [comment]
Hi, 
Thanks for your interest in our EasyCodeML. For your results presented in the Excel file, the 1st column is the position of amino acids translated from the codon of your sequences, the 2nd column indicates the amino acids translated (note these   refer to the first sequence in your data), the 3rd column is posterior probability (pp) that identified codons under positive selection by the BEB analysis. Sites potentially under positive with  pp >0.95 are indicated by asterisks. I hope this is helpful.

PS, it is recommend to read our paper of EasyCodeML published in Ecology and Evolution (2019;9:3891–3898). 

All the best,
Fangluan
